### ISSUE TITLE
git_version set to 1.8.6 in all.yml

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/ofn-install#111]
https://github.com/openfoodfoundation/ofn-install/blob/master/inventory/group_vars/all.yml

```yml
git_version: v1.8.6
```

this post provides some suggestions https://stackoverflow.com/a/29157519

I would lean towards having a branch in `openfoodnetwork` repo named something like `production`, `stable`, `release` (whatever) and always have it pointing to the latest tag.

In [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) one could just use `master` but ofn seems to use `master` like gitflow `development`

**Comment by sauloperez** [comment]
Well, the thing is that we constantly use this to deploy other branches to test them in staging.

What I like of the deployment script we had back in the company we used to work for with @enricostano, is that it picked the HEAD of the branch you were in. So if I was running the script from `foo` in my local machine it got the HEAD from `origin/foo`. This way we didn't have to specify any branch, just the environment you wanted to deploy to.

In our case, while the ansible scripts live in our folder, the app you want to deploy lives in another. So hard to mimic that behavior. Perhaps the easiest thing is to allow using `GIT_VERSION` env var so that it can be provided from the command line. And we might also want to provide `GIT_REMOTE` or `GIT_FORK` to be to deploy someone else's fork of OFN. I do that a lot.

**Comment by enricostano** [comment]
Yep we should use something like https://github.com/coopdevs/timeoverflow/blob/develop/config/deploy.rb#L10

a la Capistrano...

**Comment by elf-pavlik** [comment]
I think we need 2 things
1. Sane defaults for someone getting started with a new instance
2. Flexibility for developers which need to try out different things (forks, branches)

https://github.com/openfoodfoundation/ofn-install/blob/master/inventory/group_vars/all.yml#L17
```yaml
git_repo: https://github.com/openfoodfoundation/openfoodnetwork.git
```

maybe for flexibility using ansible `--extra-vars` would work for overwriting defaults?
http://docs.ansible.com/ansible/latest/playbooks_variables.html#passing-variables-on-the-command-line

as for sane default, I don't think currently hardcoded `1.8.6` makes any sense for those who just get started

**Comment by elf-pavlik** [comment]
Thinking about small steps, setting `all.yaml` to `master` seems like an improvement over having `1.8.6` there. Most people probably will start with staging setup and `master` seems reasonable for that, later each host can overwrite it to some release version. We would also worry later how to avoid PR each time one of the hosts updates release version, for now let's just try to get rid of that default `1.8.6`.

**Comment by sauloperez** [comment]
I was about to open a PR with exactly that change when I saw your comment. Totally agree, we find ourselves deploying master to our staging lots of times.
