### ISSUE TITLE
[WARNING]: Ignoring invalid attribute: always_run

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#207]
This warning comes from `community/jdauphant.nginx/handlers/main.yml`. I checked the current master of that role and it doesn't contain that attribute. So updating our version of `jdauphant.nginx` should help with this.

**Comment by Matt-Yorkley** [comment]
Note: this should be covered by the more general issue #265 to update our community modules.

**Comment by sauloperez** [comment]
The first version of the plugin that fixes the issue is v2.8 while we're using v2.7.4. It doesn't look like a big deal, though https://github.com/jdauphant/ansible-role-nginx/compare/v2.7.4...v2.8

I prefer to this small upgrade so that we can ship it confidently and then create an issue under "Update community modules" to spend some time investigating the implications of upgrading to the latest one.
