### ISSUE TITLE
Provision and deploy France's staging with ofn-install

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#270]
We need to reprovision and then deploy France's staging server with `ofn-install`. This will require adding its configuration settings to this repo and prevent people from using it while we provision and deploy.

**Comment by Matt-Yorkley** [comment]
I'll grab this one if someone can add my SHH key to the server.

**Comment by Matt-Yorkley** [comment]
The French staging server is currently running Ubuntu 14, but ofn-install scripts will not run on less than Ubuntu 16. There are 2 applications running in containers on the staging server, for the Wordpress and forum. 

So the upgrade to 16 needs to happen before we can provision and deploy, but that might require migrating the 2 containers first, which will need some discussion/coordination.

@pacodelaluna @myriamboure

**Comment by Matt-Yorkley** [comment]
Also it looks like the old production is still available, but now it's running Ubuntu 18...? Maybe that one can be repurposed as a new staging server, and the other two apps can be left where they are?

**Comment by sauloperez** [comment]
are we sure about that? if we don't touch the machine we are certain we won't mess with it. I thought of just getting a new staging server so we touch neither those containers nor production.

In any case, it wasn't a good idea to stuff so unrelated stuff in a server IMO. It might be because I'm not very familiar with docker.

**Comment by luisramos0** [comment]
yeah, that's one of the purposes of docker @sauloperez you can put whatever you want in there without diff containers messing up with each other.
so, I'd upgrade to 16 and make sure docker is still working. it should be just fine for the WPs inside the containers.
this just needs some ack from @myriamboure and or @pacodelaluna

**Comment by pacodelaluna** [comment]
About french stage, the important information is to know that there are still 2 prod apps running on it through Docker containers: Discourse (http://forums.openfoodfrance.org) and Wordpress (https://apropos.openfoodfrance.org). The plan is to move these 2 containers on the old french prod server.
About ofn-install on stage, it seems to work good but we have very limited space on stage disk and it happens that the disk get full due to a deployment. The best would be to be sure that only the 3 last releases are kept on stage during the Docker migration period.

**Comment by sauloperez** [comment]
It's not a problem to provision a custom branch other than master modifying that number for a short while. However, have you checked the size of `log/*.log`? We don't rotate them.

**Comment by Matt-Yorkley** [comment]
So... lets mark this as blocked and open an issue to migrate those containers to the other server?

**Comment by luisramos0** [comment]
before this issue is done, If you provision the FR staging server (it's not ready for that yet), you can revert it and make the current setup work again by editing the following files:
- sudo vim /etc/nginx/sites-available/ofn_443.conf
- sudo vim /etc/init.d/unicorn_openfoodnetwork
- sudo chown offrance /etc/default/openfoodnetwork

and replace user openfoodnetwork and folder /home/openfoodnetwork with user offrance and folder /home/offrance

**Comment by Matt-Yorkley** [comment]
OK, so this is no longer blocked by #326 and can move forward. We'll need to double check which server is which (there are three) and maybe do an upgrade, then we can properly set up French staging with ofn-install and delete the old user profile and the old directories.

And then we can add Semaphore deployments as well. :tada:

**Comment by sauloperez** [comment]
As a first step I would ask you @pacodelaluna to list the URL of each server and its purpose and then we can plan ofn-installazing one of them.

**Comment by Matt-Yorkley** [comment]
Looking at the IPs it looks like
- Production is: 51.68.226.206 (https://openfoodfrance.org)
- Wordpress is: 51.255.196.10 (https://apropos.openfoodfrance.org/)
- Discourse is _also_: 51.255.196.10 (https://forums.openfoodfrance.org/)
- Staging is: 149.202.55.45 ? (http://staging.openfoodfrance.org)

So we can just update staging, which hasn't changed. Is that right, @pacodelaluna ?

**Comment by pacodelaluna** [comment]
Oh, missed these messages, don't hesitate to ping me directly on Slack if you need a quick answer.

I don't think you need to update staging IP, we will still use the same server for staging, now we can break what we want on staging as Discourse and Wordpress as been migrated to an other server.

Please feel free to reinstall the staging server, you should have all the details required, I have shared everything in Bitwarden, but please tell me if you face any issue.

**Comment by luisramos0** [comment]
hello @Matt-Yorkley we are entering a intense phase of v2 testing so we need this server. Would you have time to do this week?
if not, I will pick it up, could you please guide me here?
My plan would be to wipe the server clean (delete docker for example) and get it to ubuntu 16.
How to upgrade ubuntu to v16? (otherwise I'll go for the usual cocktail of google+brain+trial+error)

**Comment by Matt-Yorkley** [comment]
Technically I think it's considered best practice is to start with a fresh server rather than do an in-place upgrade. So maybe that's the best option. Which i think means @pacodelaluna would have to reset the server and set it to Ubuntu 16 via the OVH control panel.

**Comment by Matt-Yorkley** [comment]
Ah, it looks like I still have OVH access, I'll take a look.

**Comment by RachL** [comment]
FYI OVH access are in Bitwarden if needed :)

**Comment by Matt-Yorkley** [comment]
Okay, our Semaphore servers list has a new kid on the block:
![Screenshot-2019-03-26-14-58:44](https://user-images.githubusercontent.com/9029026/55007696-c8fb8300-4fd7-11e9-8e09-f773dae7d349.png)

**Comment by Matt-Yorkley** [comment]
I hit a couple of fatal errors whilst running the `site.yml` playbook, I'll add some issues to address them.

**Comment by Matt-Yorkley** [comment]
Closing as completed.

**Comment by luisramos0** [comment]
fabulous 💯
