### ISSUE TITLE
Increase number of unicorn workers for UK prod

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/ofn-install#355]
UK (like other instances) is experiencing intermittent site failures. When this happens any user that tries to access any page on [openfoodnetwork.org.uk](openfoodnetwork.org.uk) gets an error meaning that to the user is appears that OFN UK is totally down. This goes away on a refresh (or possibly two refreshes).

**Possible Cause**
After many conversations with @luisramos0 and @sauloperez I have come to deduce a probable cause. UK (like most instances) has two unicorn workers. When both of these workers are occupied with other requests no other users can access the site at all. This is increasingly common due to the many performance issues we face in OFN (and we won't go into these here). Two large reports or data heavy pages loading at the same time can take minutes and stop others accessing OFN during this time.

**Relevant Background**
We have two unicorn workers based on experimentation in Australia (according to @mkllnk). The number of unicorn workers is limited by the server memory. Another possible limitation is the number of DB connections, though I am sure that our connection pools have more than 2 connections so this shouldn't be a direct limitation in the same way that the number of workers is.

@sauloperez informs me that, based on Datadog monitoring, UK is not using close to its maximum memory. Therefore we feel confident we can try increasing the number of unicorn workers to 3 on UK prod to see if this helps the issue.

**Possible Solution**
Updating configuration such that unicorn starts with 3 workers in UK servers only. If this is successful other instances might be interested in doing this too.

**Comment by mkllnk** [comment]
:+1: Go ahead.

Some more background: If I remember correctly, we had only 2 GB of memory in 2014 when I joined the team. This was usually okay but sometimes the server would crash because it ran out of memory. So we doubled to 4 GB. That went okay for a while, but at some point it started crashing again. I think it crashed when people tried to upload large images. The image conversion needed lots of memory and it crashed the server. We were talking about improving the admin interface to deal with that. Instead we just doubled the memory again.

When I last looked into image uploads, it seemed to have a reasonable limit. Maybe there is a form without limit that I'm not aware of. But if one process needs lots of memory but only very few times then that can be covered with a swap file. We didn't have a swap file in all those years.

Now I think you could probably have lots more workers with a swap file. It's good to monitor performance though, especially swap usage. But I would guess that you could have 7 workers with 8 GB of memory. Your plan to increase only by one at a time seems a very good approach to me. I would like to do the same in Aus because we have the same problem.

A few nights ago, somebody in Europe triggered ten requests to `/shops` in a very short time and the server was down for 20 minutes. Lucky it was 3am here.

**Comment by Matt-Yorkley** [comment]
LETS DO IT!

![](https://media.giphy.com/media/nb2NsnrPOH3SU/giphy.gif)

**Comment by sauloperez** [comment]
> A few nights ago, somebody in Europe triggered ten requests to /shops in a very short time and the server was down for 20 minutes. Lucky it was 3am here.

I would feel much better being aware of those downtimes as well. Otherwise, we miss the whole picture. There are no Slack notifications for alarms in AU, right?

**Comment by mkllnk** [comment]
> There are no Slack notifications for alarms in AU, right @mkllnk ?

We always had a webhook for the #aus channel. Now I added one for #devops-notifications so that you can see it as well.

I find that channel too noisy though. I'm not paying attention any more. I get text alerts to my phone if the Australian server is down.
