### ISSUE TITLE
FR prod registration link and password reset link not in https

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#750]
## Description

When you register in FR prod or you ask for a new password, the link that enables you to confirm your email or change your password is not sent in https. It means that Chrome users can't use it.

## Steps to Reproduce

Scenario 1

1. Register on coopcircuits.fr
2. See link

Scenario 2

1. Ask to change your password on coopcircuits.fr

## Animated Gif/Screenshot

Example of link for registration : http://url8344.coopcircuits.fr/ls/click?upn=lmR-2F06NxyjYuMDwwrJrG9K-2B0-2Bh9mxOqA-2BCKfPYTkPSIJsLU6D5E0LhKD8RLENOngDH3bN7yR97lvghmnjy5nKdj1Kq9wC64tVlNgUvTEquXU7QDTTZPYi7kovFCPCpgqdCLsyA1G-2B72DQY-2FwhCFlwg-3D-3Do0mo_VIH3-2Bha1squ3Hk0F8PoA7PZbxXKoQU3mPEDm-2F5gt93u7ZOZnqHc6cJGz-2FBT46k5J8jB7KJ2LfVJZGlI1ukYR9Jl1Ljs-2FMqbFKk5eMmu0SxamaCteTjLGsP9dB0UkTq0S38Hza9jwGB7g3aWVxpr7QvvWvGeWCHPPvoKju4X5VMV7hRcXtLIw2-2Bq-2BxGLozUrsBEqUbqQecP68H5keClle-2FIobnRinCeg5dnnGCN5Rl4XQWxICCwddkaelxEDjIbcM

![image](https://user-images.githubusercontent.com/6525576/120883760-4cb15100-c5df-11eb-9e4f-512ce9c3802e.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): both

## Possible Fix

Fix SSL cert

**Comment by jibees** [comment]
Tested with the last chrome (91.0.4472.77): worked for me, no error messages. Maybe due to changes into the last chrome version?
Saying that, the link is still in http (not `s`): we need to fix that.

I presume that the correction may have to be made in our email configuration (I think it has nothing to do with the OFN code base).

**Comment by sauloperez** [comment]
https://stackoverflow.com/a/23664482 is the first thing I'd check. It's Rails who builds the URLs used in emails.

**Comment by jibees** [comment]
@sauloperez 
The thing is that in staging, the url is well in `https`. That's why I think more about a configuration issue around sendgrid between the two environments.

**Comment by pacodelaluna** [comment]
The issue is related to Sendgrid which is actually rewriting urls for their tracking purpose. As we are using the Branding Link feature, we need to setup a proxy in order to manage HTTPS requests as Sendgrid cannot deal with SSL for us, https://sendgrid.com/docs/ui/account-and-settings/custom-ssl-configurations/. The documentation is not super clear to me, I mean I am not so much confident about how to set this up, I have requested an example from Sengrid.

**Comment by pacodelaluna** [comment]
After getting more information from @Matt-Yorkley, it seems that only France instance was using Link Tracking feature at Sendgrid side. So I decided to switch it off in order to have the simplest setup possible.
![Screenshot from 2021-06-08 14-07-04](https://user-images.githubusercontent.com/27745/121184012-f2c1bd00-c864-11eb-9d14-5109d2ea1242.png)

**Comment by pacodelaluna** [comment]
It worked like a charm, I just needed to restart the unicorn process to have the new configuration effective in FR prod instance
Thanks for you all for your help!

**Comment by pacodelaluna** [comment]
Ok, there was a direct side effect, links in old emails were not working anymore, I was expecting Sendgrid to keep the redirection for sometimes. Not such a big issue apart for fresh orders I guess.

**Comment by RachL** [comment]
Everything is now in https! Thanks team ❤️

**Comment by sauloperez** [comment]
Cool @pacodelaluna ! if someone complains, you can tell them to go to the HTTPS version of the URL
